bot:
  inspection: hint-grayskull
build_platform:
  linux_aarch64: linux_64
  # fails with: unknown relocation (31) against symbol aws_lc_0_36_0_OPENSSL_realloc
  # linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
